outputPath: c:\temp\Generated project\ChamExtension
templatesPath: C:\source\CodeAutomation\data\templates\ChamExtension
config:
  project:
    customer: Customer
    name: DemoProject
dataSource:
  settingsProcessor: default
  dataSourceType: csv
  culture: en-AU
  connectionString: c:\temp\Csv