contractor: GFG
projectName: SomeProject
csvPath: c:\temp\Csv
templatesPath: C:\source\CodeAutomation\data\templates
outputPath: c:\temp\Generated project
multipleValues:
- value: testValue1
  nested:
  - value: nestedValue1
  - value: nestedValue2
- value: testValue2
- value: testValue3